project:
  type: website
  output-dir: docs

format:
  html:
    theme: cosmo
    css: styles.css

    page-layout: full
    grid:
      sidebar-width: 280px
      body-width: 1400px
      margin-width: 240px
      gutter-width: 0.6rem

    toc: true
    toc-location: right
    toc-title: "목차"
    toc-depth: 4


website:
  title: "세상의 모든 통계 이야기"

  navbar:
    left:
      - text: "기초수학·수리통계"
        href: notes/math_stat/index.qmd
      - text: "기초통계|조사방법"
        href: notes/intro_stat/index.qmd
      - text: "회귀·다변량분석"
        href: notes/linear_model/index.qmd
      - text: "MLDL개념"
        href: notes/mldl_intro/index.qmd
      - text: "MLDL예측"
        href: notes/mldl_prediction/index.qmd
      - text: "MLDL분류"
        href: notes/mldl_classification/index.qmd
      - text: "차원축소|군집|인과추론・XAI"
        href: notes/data_reduction/index.qmd
      - text: "카드뉴스"
        href: cardnews/index.qmd
      - text: "통계상담"
        href: consult.qmd

  sidebar:
    - id: math_stat
      title: "기초|수리통계"
      style: docked
      search: false
      contents: 
        - href: notes/math/index.qmd
          text: "【기초수학】"
        - href: notes/math/function.qmd
          text: "📄 함수"
        - href: notes/math/derivate_integral.qmd
          text: "📄 미분적분"
        - href: notes/math/vector.qmd
          text: "📄 벡터"
        - href: notes/math/matrix.qmd
          text: "📄 행렬" 
        - href: notes/math_stat/index.qmd
          text: "【수리통계】"
        - href: notes/math_stat/probability.qmd
          text: "📄 확률"
        - href: notes/math_stat/random_variable.qmd
          text: "📄 확률변수"
        - href: notes/math_stat/famous_distribution.qmd
          text: "📄 유명한 분포"
        - href: notes/math_stat/multi_variate.qmd
          text: "📄 다변량확률변수"
        - href: notes/math_stat/random_sample.qmd
          text: "📄 확률표본·난수"
        - href: notes/math_stat/estimation.qmd
          text: "📄 추정"
        - href: notes/math_stat/hypothesis_testing.qmd
          text: "📄 가설검정·신뢰구간"
              
    - id: intro_stat
      title: "기초통계"
      style: docked
      search: false
      contents:
        - href: notes/intro_stat/index.qmd
          text: "【기초통계】"
        - href: notes/intro_stat/concept_of_stat.qmd
          text: "📄 통계학의 개념"
        - href: notes/intro_stat/data.qmd
          text: "📄 데이터와 통계"
        - href: notes/intro_stat/univariate.qmd
          text: "📄 일변량 분석"
        - href: notes/intro_stat/crosstab.qmd
          text: "📄 교차표 분석"
        - href: notes/intro_stat/goodness_of_fits.qmd
          text: "📄 적합성 검정"
        - href: notes/intro_stat/normality.qmd
          text: "📄 정규성 검정"
        - href: notes/intro_stat/correlation.qmd
          text: "📄 상관분석"
        - href: notes/intro_stat/anova.qmd
          text: "📄 분산분석(ANOVA)"
        - href: notes/intro_stat/time_series.qmd
          text: "📄 시계열 분석"
        - href: notes/survey/index.qmd
          text: "【조사방법론】"
        - href: notes/survey/survey_intro.qmd
          text: "📄 조사방법 기초"
        - href: notes/survey/sample_design.qmd
          text: "📄 표본설계"
        - href: notes/survey/questionnaire.qmd
          text: "📄 설문지"
        - href: notes/survey/nonresponse.qmd
          text: "📄 무응답 대체"
        - href: notes/survey/data_process.qmd
          text: "📄 데이터 처리"
        - href: notes/survey/survey_scale.qmd
          text: "📄 조사지 척도"
        - href: notes/survey/delphi_ahp_conjoint.qmd
          text: "📄 델파이·AHP·컨조인트"
        - href: notes/survey/psm.qmd
          text: "📄 PSM 성향점수매칭"

    - id: linear_model
      title: "회귀분석"
      style: docked
      search: false
      contents:
        - href: notes/linear_model/index.qmd
          text: "【회귀분석】"
        - href: notes/linear_model/lm_concept.qmd
          text: "📄 개념·추정"
        - href: notes/linear_model/lm_selection.qmd
          text: "📄 변수선택"
        - href: notes/linear_model/lm_multicolin.qmd
          text: "📄 다중공선성"
        - href: notes/linear_model/lm_diagnosis.qmd
          text: "📄 회귀진단"
        - href: notes/linear_model/lm_logistic.qmd
          text: "📄 로지스틱회귀"
        - href: notes/mda/index.qmd
          text: "【다변량분석】"
        - href: notes/mda/mda_concepts.qmd
          text: "📄 개요"
        - href: notes/mda/mda_pca.qmd
          text: "📄 PCA"
        - href: notes/mda/mda_factor.qmd
          text: "📄 요인분석"
        - href: notes/mda/mda_cluster.qmd
          text: "📄 군집분석"
        - href: notes/mda/mda_discriminant.qmd
          text: "📄 판별분석"
        - href: notes/mda/mda_mds_ca.qmd
          text: "📄 다차원척도·대응분석"
        - href: notes/mda/mda_cancorr_manova.qmd
          text: "📄 정준상관·MANOVA"

    - id: mldl_intro
      title: "머신·딥러닝 개념"
      style: docked
      search: false
      contents:
        - href: notes/mldl_intro/index.qmd
          text: "【머신·딥러닝 개념】"
        - href: notes/mldl_intro/mldl_concepts.qmd
          text: "📄 개요"
        - href: notes/mldl_intro/mldl_concepts01.qmd
          text: "📄 MLDL 개념 1"
        - href: notes/mldl_intro/mldl_concepts02.qmd
          text: "📄 MLDL 개념 2"
        - href: notes/mldl_intro/mldl_supervised.qmd
          text: "📄 지도학습"
        - href: notes/mldl_intro/mldl_unsupervised.qmd
          text: "📄 비지도학습"
        - href: notes/mldl_intro/mldl_evaluation.qmd
          text: "📄 MLDL 평가"
        - href: notes/mldl_intro/mldl_uncertainty.qmd
          text: "📄 불확실성"
        - href: notes/mldl_intro/method_intro.qmd
          text: "📄 MLDL 기초"
        - href: notes/mldl_intro/mldl_deep_concepts.qmd
          text: "📄 딥러닝 기초"

    - id: mldl_prediction
      title: "머신·딥러닝 방법론 예측문제"
      style: docked
      search: false
      contents:
        - href: notes/mldl_prediction/index.qmd
          text: "【머신·딥러닝 예측방법】"
        - href: notes/mldl_prediction/prediction_intro.qmd
          text: "📄 예측문제 개요"
        - href: notes/mldl_prediction/prediction_regression.qmd
          text: "📄[전통] 회귀분석"
        - href: notes/mldl_prediction/prediction_regulation.qmd
          text: "📄[전통] 규제회귀"
        - href: notes/mldl_prediction/prediction_dimension.qmd
          text: "📄[전통] 차원축소"
        - href: notes/mldl_prediction/prediction_nonreg.qmd
          text: "📄[머신러닝] 비선형회귀"
        - href: notes/mldl_prediction/prediction_treebase.qmd
          text: "📄[머신러닝] 트리기반"
        - href: notes/mldl_prediction/prediction_deeplearning.qmd
          text: "📄 딥러닝회귀"

    - id: mldl_classification
      title: "머신·딥러닝 방법론 분류문제"
      style: docked
      search: false
      contents:
        - href: notes/mldl_classification/index.qmd
          text: "【머신·딥러닝 분류문제】"
        - href: notes/mldl_classification/classification_intro.qmd
          text: "📄 분류문제: 정의"
        - href: notes/mldl_classification/lm_logistic.qmd
          text: "📄 예측분류-로지스틱회귀"
        - href: notes/mldl_classification/mda_discriminant.qmd
          text: "📄 예측분류-판별분석"
        - href: notes/mldl_classification/prediction_treebase.qmd
          text: "📄 예측분류-ML 트리기반"
        - href: notes/mldl_classification/classification_ml_methods.qmd
          text: "📄 머신러닝 kNN SVM 이론"
        - href: notes/mldl_classification/classification_evaluation.qmd
          text: "📄 분류모델 평가"
        - href: notes/mldl_classification/classification_ml_case_binary.qmd
          text: "📄 머신러닝 이진형 사례"
        - href: notes/mldl_classification/classification_ml_case_category.qmd
          text: "📄 머신러닝 k>=3 사례"
        - href: notes/mldl_classification/classification_deeplearning.qmd
          text: "📄 딥러닝 분류 이론"
        - href: notes/mldl_classification/classification_dl_rare_case.qmd
          text: "📄 딥러닝 분류 (희소성공)사례"
        - href: notes/mldl_classification/classification_dl_image_case.qmd
          text: "📄 딥러닝 분류 (이미지)사례"
        - href: notes/mldl_classification/classification_dl_text_case.qmd
          text: "📄 딥러닝 분류 (텍스트)사례"

    - id: data_reduction
      title: "머신·딥러닝 차원축소|군집|인과추론|XAI"
      style: docked
      search: false
      contents:
        - href: notes/data_reduction/index.qmd
          text: "【차원축소】"
        - href: notes/data_reduction/data reduction_intro.qmd
          text: "📄 차원축소 개념|필요성"
        - href: notes/data_reduction/data reduction_statmethod.qmd
          text: "📄 차원축소 통계적방법"
        - href: notes/data_reduction/data reduction_unsupervised.qmd
          text: "📄 차원축소 비지도학습"
        - href: notes/data_reduction/data reduction_case.qmd
          text: "📄 차원축소 사례분석"
        - href: notes/mldl_clustering/index.qmd
          text: "【군집・비지도학습】"
        - href: notes/mldl_clustering/clustering_intro.qmd
          text: "📄 군집・비지도학습 개념"
        - href: notes/mldl_clustering/clustering_method.qmd
          text: "📄 군집・비지도학습 방법론"
        - href: notes/mldl_clustering/clustering_case.qmd
          text: "📄 군집・비지도학습 사례분석"
        - href: notes/inference_xai/index.qmd
          text: "【인과추론|설명가능 AI】"
        - href: notes/inference_xai/casual_inference.qmd
          text: "📄 인과추론 개념"
        - href: notes/inference_xai/explainable_ai.qmd
          text: "📄 설명가능 AI 개념"
